### ISSUE TITLE
Need to use `isDeactivated` field in middleware

### ISSUE THREAD

**Issue by Gauravdarkslayer** [rwiteshbera/StoryVerse#12]
Need to use `isDeactivated` field in middleware. If user is deactivated then on the api call we can send `401` response code directly from the middleware function.

**Comment by rwitesh** [comment]
This is great! Even we can redirect them to the `/login` page. Go for it.

**Comment by Gauravdarkslayer** [comment]
Yeah! I will create a separate issue for this task you mentioned.

**Comment by rwitesh** [comment]
> Yeah! I will create a separate issue for this task you mentioned.

Sure
