### ISSUE TITLE
[Documentation] Write Contribution guidelines and add it to README.md

### ISSUE THREAD

**Issue by rwitesh** [rwiteshbera/StoryVerse#16]
1. Create a `Contribution.md` in the `root` directory.
2. Write how to contribute to this GitHub project describing the following task. 
- Fork
- Clone
- Branch creation
- Make changes
- Add and push
- Make valid PR with proper description
3. Link the `Contribution.md` file with `README.md` file.

**Comment by yash-sharma13** [comment]
I'll do it

**Comment by atharvai812** [comment]
Assign Me

**Comment by rwitesh** [comment]
> I'll do it

Assigned 👍

**Comment by AkshayGidwani405** [comment]
**sabko t shirts chahiye bss**

**Comment by AkshayGidwani405** [comment]
Laughing emoji add krna rhe gya

**Comment by rwitesh** [comment]
> Laughing emoji add krna rhe gya

Please maintain the environment of this section. You can contribute to other valid issues. Thank you.
