### ISSUE TITLE
[Bug] Fix 'await' expressions are only allowed within async functions and at the top levels of modules.

### ISSUE THREAD

**Issue by rwitesh** [rwiteshbera/StoryVerse#18]
#### Fix the `requireLogin.js` middleware file inside the `server` folder that is breaking the app.
File Location: `server\middleware\requireLogin.js`

![image](https://user-images.githubusercontent.com/73098407/194766493-1ed47a96-cd85-4e7a-b32f-60db2d4e5e56.png)

- Error: 'await' expressions are only allowed within async functions and at the top levels of modules.

**Comment by azilRababe** [comment]
add the async keyword
Write module.exports = **async** (req,res,next)=>{} 
instead of module.exports = (req,res,next)=>{}
