### ISSUE TITLE
[Warning] : Chakra UI : A component is changing an uncontrolled input of type text to be controlled.

### ISSUE THREAD

**Issue by rwitesh** [rwiteshbera/StoryVerse#8]
Warning: react_devtools_backend.js:4026 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. **MAKE SURE TO CHECK ALL INPUT TAGS**

![image](https://user-images.githubusercontent.com/73098407/194690835-5cc2838c-1b88-4e9f-92be-b8e31cdea319.png)

**Comment by jma26** [comment]
Hey @rwiteshbera! Is this issue still open? I'd love to take on this bug. Thanks!

**Comment by rwitesh** [comment]
Yeah @jma26, it is still open. Assigned! 👍
