### ISSUE TITLE
Migrate all the environment variables from keys.js to dotenv in server

### ISSUE THREAD

**Issue by rwitesh** [rwiteshbera/StoryVerse#9]
The `.env` file should contain the following secret keys.
- Keys.js
```js
module.exports = {
  MONGO_URI: "",
  JWT_SECRET_KEY: "",
  SENDER_EMAIL: "",
  SENDER_EMAIL_PASS: "",
  CLIENT_PORT_ID: 5050,
  CLOUDINARY_NAME: "",
  CLOUDINARY_API_KEY: ,
  CLOUDINARY_API_SECRET: "",
};
```
Dotenv: https://www.npmjs.com/package/dotenv
Blog: https://medium.com/@thejasonfile/using-dotenv-package-to-create-environment-variables-33da4ac4ea8f

**Comment by VarunGitGood** [comment]
Im solving this

**Comment by VarunGitGood** [comment]
there is no keys.js it is in gitignore file

**Comment by rwitesh** [comment]
Hi, @varun7singh, It is mentioned in README.md that `keys.js` contains secret keys. Hence it is given in `.gitignore`. You have to create your own `keys.js` to use it. All you have to do is migrate all the `keys.js` secret keys to `.env`. If you need any help, you can ask me.

**Comment by rwiteshbera** [comment]
All you have to do is migrate all the keys.js secret code to `.env`

**Comment by VarunGitGood** [comment]
Yeah but the env file will not be pushed so what do i name the env file

**Comment by rwitesh** [comment]
Make sure you have configured the dotenv package in the server and that they are properly working. Then just update the README like
- Create a `.env` file inside `server` folder. Copy the following code
  snippet add all the secret keys.
  - add your code snippet

**Comment by rwitesh** [comment]
Hi @varun7singh, if you need any help, you can ask me.

**Comment by Gauravdarkslayer** [comment]
Hi @rwiteshbera , should i pick this issue or @varun7singh is still on it ?

**Comment by rwitesh** [comment]
> Hi @rwiteshbera , should i pick this issue or @varun7singh is still on it ?

Ok, Let me assign it to you. If anyone makes valid PR first. I will merge it.
